wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.12
    cli_version: 0.16.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705281363.494755
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.7.12
      5: 0.16.0
      8:
      - 5
      13: darwin-x86_64
