wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1705456822.167187
    t:
      1:
      - 53
      - 55
      2:
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.16.2
      8:
      - 1
      - 5
      13: darwin-x86_64
